### ISSUE TITLE
NA handling in formatPval

### ISSUE THREAD

**Issue by ks-uz** [felix-hof/biostatUZH#1]
Maybe the formatPval function should handle NA without an error.

biostatUZH::formatPval(x = NA) # should maybe not throw an error 
biostatUZH::formatPval(x = c(0.3, NA_real_)) # still throws an error

**Comment by felix-hof** [comment]
Thanks for the notification. The issue should be resolved with commit [b05b331](https://github.com/felix-hof/biostatUZH/commit/b05b3310c2dd873e2e028113d59037f51518495d). I will close this issue now but feel free to reopen if you are still experiencing unexpected behavior.
